name: "Benchmarks: Remove Data on Closed PRs"

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  benchmark_base_branch:
    name: Archive closed PR branch with Bencher
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
      - name: Archive closed PR branch with Bencher
        run: |
          bencher archive \
          --project fandango-394f926-x0wdsa1zilqt3 \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch "${{ github.head_ref }}"

    
