name: Build and deploy Docs

on:
  pull_request:
  workflow_dispatch: # Allows manual triggering from the Actions tab
  push:
    branches: [ release ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the source repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Fandango
      - name: Install Fandango
        uses: ./.github/workflows/setup-fandango
        with:
          python-version: 3.13
          needs-sudo: true
      
      # Step 3: Build the documentation
      - name: Build the book
        shell: bash
        run: |  
          sudo make system-dev-tools
          make web
          echo "Exit code: $?"

      # Step 4: Upload built book as artifact
      - name: Upload built book as artifact
        uses: actions/upload-artifact@v4
        with:
          name: book-html
          path: docs/_build/html/

  deploy:
    # Only deploy on pushes to the release branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/release'
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the source repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Download built book artifact
      - name: Download built book artifact
        uses: actions/download-artifact@v4
        with:
          name: book-html
          path: htmlcov

      # Step 3: Clone the target repository
      - name: Clone the target repository
        run: |
          git clone https://github.com/fandango-fuzzer/fandango-fuzzer.github.io.git gh-pages

      # Step 4: Copy the built HTML files to the target repository
      - name: Copy built files to the target repository
        run: |
          cp -r htmlcov/* gh-pages/

      # Step 5: Commit and push changes to the target repository
      - name: Deploy to GitHub Pages
        run: |
          cd gh-pages
          git config --global user.name "${{ secrets.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ secrets.CI_COMMIT_EMAIL }}"
          git add .
          git commit -m "Update GitHub Pages site" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/fandango-fuzzer/fandango-fuzzer.github.io.git main
